version: '{build}'
configuration:
- Release
- Debug
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
artifacts:
  - path: 
nuget:  
  disable_publish_on_pr: true
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: oWOc0aKSOVW3aAv0rUSQGmF509P29wxdOakJ5ZNThtxtCVd0pYpk8XyiN9pXWXVY
  on:
    branch: master
    appveyor_repo_tag: true